INSERT INTO `settings` 
    (`title`, `settings_key`, `settings_value`, `settings_group`, `settings_type`, `status`, `sort`, `required`, `updated_on`) 
VALUES
    ('Brand Name', 'brand_name', 'Brand name', 'site', 'text', 1, 1, 1, NULL),
    ('Site name', 'site_name', 'My awesome website', 'site', 'text', 1, 2, 1, NULL),
    ('Site info', 'site_info', 'Welcome to my awesome website!', 'site', 'text', 1, 3, 1, NULL),
    ('Administrator email', 'administrator_email', 'admin@domain.com', 'site', 'email', 1, 4, 1, NULL),
    ('Site status', 'site_status', '1', 'site', 'yes/no', 1, 5, 1, NULL),
    ('Status message', 'unavailable_message', 'The website is in maintenance mode!', 'site', 'text', 1, 6, 1, NULL),
    ('Password protection', 'site_password_protection', '1', 'site', 'yes/no', 1, 7, 1, NULL),
    ('Password', 'site_password', REPLACE(ROUND((99999 - 10000 * RAND()), 0), '.00', ''), 'site', 'text', 1, 8, 1, NULL),
    ('Site logo', 'site_logo', '', 'site', 'file', 1, 9, 0, NULL),
    ('Site favicon', 'site_favicon', '', 'site', 'file', 1, 10, 0, NULL),
    ('Multi language', 'multi_language', '0', 'general', 'yes/no', 1, 1, 1, NULL),
    ('Site language', 'site_language', 'en', 'general', 'languages_dropdown', 1, 2, 1, NULL),
    ('Character encoding', 'site_charset', 'UTF-8', 'general', 'text', 1, 3, 1, NULL),
    ('Timezone', 'timezone', 'Asia/Tashkent', 'general', 'timezone_dropdown', 1, 4, 1, NULL),
    ('Webmaster email', 'webmaster_email', 'info@domain.com', 'general', 'email', 1, 5, 1, NULL),
    ('Default currency', 'site_currency', 'USD', 'general', 'currency_dropdown', 1, 6, 1, NULL),
    ('Price format', 'price_format', '1', 'general', 'price_format_dropdown', 1, 7, 1, NULL),
    ('Currency format', 'currency_format', '{{currency}} {{price}}', 'general', 'text', 1, 8, 1, NULL),
    ('Phone number', 'phone_number', '', 'contacts', 'phone', 1, 1, 0, NULL),
    ('Mobile number', 'mobile_number', '', 'contacts', 'phone', 1, 2, 0, NULL),
    ('Fax number', 'fax_number', '', 'contacts', 'phone', 1, 3, 0, NULL),
    ('Email address', 'email_address', '', 'contacts', 'email', 1, 4, 0, NULL),
    ('Company address', 'company_address', '', 'contacts', 'text', 1, 5, 0, NULL),
    ('Google Map', 'google_map', '', 'contacts', 'text', 1, 6, 0, NULL),
    ('Skype', 'skype_address', '', 'contacts', 'text', 1, 7, 0, NULL),
    ('Whatsapp', 'whatsapp_number', '', 'contacts', 'text', 1, 8, 0, NULL),
    ('Telegram', 'telegram_number', '', 'contacts', 'text', 1, 9, 0, NULL),
    ('Viber', 'viber_number', '', 'contacts', 'text', 1, 10, 0, NULL),
    ('Facebook', 'social_fb', '', 'social', 'text', 1, 1, 0, NULL),
    ('Instagram', 'social_instagram', '', 'social', 'text', 1, 2, 0, NULL),
    ('Linkedin', 'social_linkedin', '', 'social', 'text', 1, 3, 0, NULL),
    ('Pinterest', 'social_pinterest', '', 'social', 'text', 1, 4, 0, NULL),
    ('Twitter', 'social_twitter', '', 'social', 'text', 1, 5, 0, NULL),
    ('Youtube', 'social_youtube', '', 'social', 'text', 1, 6, 0, NULL),
    ('Site theme', 'site_theme', '', 'system', 'text', 1, 0, 0, NULL),
    ('SEO title', 'seo_title', '[[title]] [[separator]] [[site_name]]', 'seo', 'text', 1, 1, 0, NULL),
    ('Title separator', 'seo_separator', '&bull;', 'seo', 'text', 1, 2, 0, NULL),
    ('SEO description', 'seo_description', '', 'seo', 'text', 1, 3, 0, NULL),
    ('Disable robots', 'seo_disable_robots', '0', 'seo', 'yes/no', 1, 4, 5, NULL),
    ('Organization name', 'seo_organization_name', '', 'seo', 'text', 1, 5, 0, NULL),
    ('Organization logo', 'seo_organization_logo', '', 'seo', 'image', 1, 6, 0, NULL);