<?php
// rollar va dostup
return [

    /* Rector */
    'rector' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'area_view',
        'citizenship_view',
        'country_view',


        'notification_create',
        'notification_delete',
        'notification_index',
        'notification_my',

        'notification_update',
        'notification_view',

        'region_view',

        // 'user_view',

        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////

        // statistic
        'statistic_student-count-by-faculty',


        'job_index',
        'job_create',
        'job_update',
        'job_view',
        'job_delete',
    ],

    /* Pro rektor */
    'prorector' => [

        'user_oferta',
        "academic-degree_create",
        "academic-degree_delete",
        "academic-degree_index",
        "academic-degree_update",
        "academic-degree_view",
        "access-control_create-role",
        "access-control_delete-role",
        "access-control_permissions",
        "access-control_role-permissions",
        "access-control_roles",
        "access-control_update-role",
        "area_create",
        "area_delete",
        "area_index",
        "area_update",
        "area_view",
        "attend-reason_create",
        "attend-reason_delete",
        "attend-reason_index",
        "attend-reason_update",
        "attend-reason_view",
        "attend_create",
        "attend_delete",
        "attend_index",
        "attend_update",
        "attend_view",
        "building_create",
        "building_delete",
        "building_index",
        "building_update",
        "building_view",
        "category-of-cohabitant_create",
        "category-of-cohabitant_delete",
        "category-of-cohabitant_index",
        "category-of-cohabitant_update",
        "category-of-cohabitant_view",
        "citizenship_create",
        "citizenship_delete",
        "citizenship_index",
        "citizenship_update",
        "citizenship_view",
        "club-category_create",
        "club-category_delete",
        "club-category_index",
        "club-category_update",
        "club-category_view",
        "club-time_create",
        "club-time_delete",
        "club-time_index",
        "club-time_update",
        "club-time_view",
        "club_create",
        "club_delete",
        "club_index",
        "club_update",
        "club_view",
        "contract_create",
        "contract_delete",
        "contract_index",
        "contract_update",
        "contract_view",
        "country_index",
        "country_view",
        "course_create",
        "course_delete",
        "course_index",
        "course_update",
        "course_view",
        "degree-info_create",
        "degree-info_delete",
        "degree-info_index",
        "degree-info_update",
        "degree-info_view",
        "degree_create",
        "degree_delete",
        "degree_index",
        "degree_update",
        "degree_view",
        "department_create",
        "department_delete",
        "department_index",
        "department_types",
        "department_update",
        "department_user-access",
        "department_view",
        "diploma-type_create",
        "diploma-type_delete",
        "diploma-type_index",
        "diploma-type_update",
        "diploma-type_view",
        "direction-info_create",
        "direction-info_delete",
        "direction-info_index",
        "direction-info_update",
        "direction-info_view",
        "direction_create",
        "direction_delete",
        "direction_index",
        "direction_update",
        "direction_view",
        "edu-form_create",
        "edu-form_delete",
        "edu-form_index",
        "edu-form_update",
        "edu-form_view",
        "edu-plan_create",
        "edu-plan_delete",
        "edu-plan_index",
        "edu-plan_update",
        "edu-plan_view",
        "edu-semestr-exams-type_create",
        "edu-semestr-exams-type_delete",
        "edu-semestr-exams-type_index",
        "edu-semestr-exams-type_update",
        "edu-semestr-exams-type_view",
        "edu-semestr-subject-category-time_create",
        "edu-semestr-subject-category-time_delete",
        "edu-semestr-subject-category-time_index",
        "edu-semestr-subject-category-time_update",
        "edu-semestr-subject-category-time_view",
        "edu-semestr-subject_create",
        "edu-semestr-subject_delete",
        "edu-semestr-subject_index",
        "edu-semestr-subject_update",
        "edu-semestr-subject_view",
        "edu-semestr_create",
        "edu-semestr_delete",
        "edu-semestr_index",
        "edu-semestr_update",
        "edu-semestr_view",
        "edu-type_create",
        "edu-type_delete",
        "edu-type_index",
        "edu-type_update",
        "edu-type_view",
        "edu-year_create",
        "edu-year_delete",
        "edu-year_index",
        "edu-year_update",
        "edu-year_view",
        "election-candidate_create",
        "election-candidate_delete",
        "election-candidate_index",
        "election-candidate_update",
        "election-candidate_view",
        "election-vote_create",
        "election-vote_delete",
        "election-vote_index",
        "election-vote_update",
        "election-vote_view",
        "election_create",
        "election_delete",
        "election_index",
        "election_password",
        "election_update",
        "election_view",
        "employee_bind-subject",
        "employee_create",
        "employee_delete",
        "employee_index",
        "employee_subjects",
        "employee_update",
        "employee_view",
        "enum_disability-groups",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-appeal-semeta_create",
        "exam-appeal-semeta_delete",
        "exam-appeal-semeta_index",
        "exam-appeal-semeta_update",
        "exam-appeal-semeta_view",
        // "exam-appeal_create",
        "exam-appeal_delete",
        "exam-appeal_index",
        // "exam-appeal_update",
        "exam-appeal_view",
        "exam-checking_appeal",
        "exam-checking_create",
        "exam-checking_index",
        "exam-checking_update",
        "exam-checking_view",
        "exam-control-student_create",
        "exam-control-student_delete",
        "exam-control-student_index",
        "exam-control-student_update",
        "exam-control-student_view",
        "exam-control_create",
        "exam-control_delete",
        "exam-control_index",
        "exam-control_update",
        "exam-control_view",
        "exam-question-option_create",
        "exam-question-option_delete",
        "exam-question-option_index",
        "exam-question-option_update",
        "exam-question-option_view",
        "exam-question-type_create",
        "exam-question-type_delete",
        "exam-question-type_index",
        "exam-question-type_update",
        "exam-question-type_view",
        "exam-question_create",
        "exam-question_delete",
        "exam-question_index",
        "exam-question_update",
        "exam-question_view",
        "exam-semeta_create",
        "exam-semeta_delete",
        "exam-semeta_index",
        "exam-semeta_update",
        "exam-semeta_view",
        "exam-student-answer_appeal",
        "exam-student-answer_create",
        "exam-student-answer_delete",
        "exam-student-answer_get-question",
        "exam-student-answer_index",
        "exam-student-answer_update",
        "exam-student-answer_view",
        "exam-student_correct",
        "exam-student_delete",
        "exam-student_index",
        "exam-student_view",
        "exam-teacher-check_create",
        "exam-teacher-check_delete",
        "exam-teacher-check_index",
        "exam-teacher-check_random-students",
        "exam-teacher-check_update",
        "exam-teacher-check_view",
        "exams-type_create",
        "exams-type_delete",
        "exams-type_index",
        "exams-type_update",
        "exams-type_view",
        "exam_ad",
        "exam_appeal-distribution",
        "exam_create",
        "exam_delete",
        "exam_distribution",
        "exam_generate-passwords",
        "exam_get-passwords",
        "exam_index",
        "exam_update",
        "exam_view",
        "faculty_create",
        "faculty_delete",
        "faculty_index",
        "faculty_update",
        "faculty_user-access",
        "faculty_view",
        "get-teacher_index",
        "holiday_create",
        "holiday_delete",
        "holiday_index",
        "holiday_update",
        "holiday_view",
        "hostel-app_create",
        "hostel-app_delete",
        "hostel-app_index",
        "hostel-app_update",
        "hostel-app_view",
        "hostel-category-type_create",
        "hostel-category-type_delete",
        "hostel-category-type_index",
        "hostel-category-type_update",
        "hostel-category-type_view",
        "hostel-category_create",
        "hostel-category_delete",
        "hostel-category_index",
        "hostel-category_update",
        "hostel-category_view",
        "hostel-doc_check",
        "hostel-doc_create",
        "hostel-doc_delete",
        "hostel-doc_index",
        "hostel-doc_not",
        "hostel-doc_update",
        "hostel-doc_view",
        "instruction_create",
        "instruction_delete",
        "instruction_index",
        "instruction_update",
        "instruction_view",
        "job-title_create",
        "job-title_delete",
        "job-title_index",
        "job-title_update",
        "job-title_view",
        "job_create",
        "job_delete",
        "job_index",
        "job_update",
        "job_view",
        "kafedra_create",
        "kafedra_delete",
        "kafedra_index",
        "kafedra_update",
        "kafedra_user-access",
        "kafedra_view",
        "kpi-category_create",
        "kpi-category_delete",
        "kpi-category_extra",
        "kpi-category_index",
        "kpi-category_update",
        "kpi-category_view",
        "kpi-data_create",
        "kpi-data_delete",
        "kpi-data_index",
        "kpi-data_update",
        "kpi-data_view",
        "kpi-mark_create",
        "kpi-mark_delete",
        "kpi-mark_index",
        "kpi-mark_update",
        "kpi-mark_view",
        "kpi-store_create",
        "kpi-store_delete",
        "kpi-store_index",
        "kpi-store_update",
        "kpi-store_view",
        "lang-certificate-type_create",
        "lang-certificate-type_delete",
        "lang-certificate-type_index",
        "lang-certificate-type_update",
        "lang-certificate-type_view",
        "lang-certificate_create",
        "lang-certificate_delete",
        "lang-certificate_index",
        "lang-certificate_update",
        "lang-certificate_view",
        "languages_create",
        "languages_delete",
        "languages_index",
        "languages_update",
        "languages_view",
        "military_create",
        "military_delete",
        "military_index",
        "military_update",
        "military_view",
        "nationality_create",
        "nationality_delete",
        "nationality_index",
        "nationality_update",
        "nationality_view",
        "notification_approved",
        "notification_create",
        "notification_delete",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_update",
        "notification_view",
        "olympic-certificate_create",
        "olympic-certificate_delete",
        "olympic-certificate_index",
        "olympic-certificate_update",
        "olympic-certificate_view",
        "order-type_create",
        "order-type_delete",
        "order-type_index",
        "order-type_update",
        "order-type_view",
        "other-certificate-type_create",
        "other-certificate-type_delete",
        "other-certificate-type_index",
        "other-certificate-type_update",
        "other-certificate-type_view",
        "other-certificate_create",
        "other-certificate_delete",
        "other-certificate_index",
        "other-certificate_update",
        "other-certificate_view",
        "para_create",
        "para_delete",
        "para_index",
        "para_update",
        "para_view",
        "partiya_create",
        "partiya_delete",
        "partiya_index",
        "partiya_update",
        "partiya_view",
        "password_index",
        "password_update",
        "password_view",
        "question-option_create",
        "question-option_delete",
        "question-option_index",
        "question-option_update",
        "question-option_view",
        "question-type_create",
        "question-type_delete",
        "question-type_index",
        "question-type_update",
        "question-type_view",
        "question_create",
        "question_delete",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_update",
        "question_view",
        "reference_create",
        "reference_delete",
        "reference_index",
        "reference_update",
        "reference_view",
        "region_create",
        "region_delete",
        "region_index",
        "region_update",
        "region_view",
        "relative-info_create",
        "relative-info_delete",
        "relative-info_index",
        "relative-info_update",
        "relative-info_view",
        "residence-status_create",
        "residence-status_delete",
        "residence-status_index",
        "residence-status_update",
        "residence-status_view",
        "room_create",
        "room_delete",
        "room_free",
        "room_index",
        "room_update",
        "room_view",
        "semestr_create",
        "semestr_delete",
        "semestr_index",
        "semestr_update",
        "semestr_view",
        "social-category_create",
        "social-category_delete",
        "social-category_index",
        "social-category_update",
        "social-category_view",
        "sport-certificate_create",
        "sport-certificate_delete",
        "sport-certificate_index",
        "sport-certificate_update",
        "sport-certificate_view",
        "statistic_checking",
        "statistic_checking-chala",
        "statistic_edu-plan",
        "statistic_exam-checking",
        "statistic_kafedra",
        "statistic_kpi-content-store",
        "statistic_student-count-by-faculty",
        "student-attend_create",
        "student-attend_delete",
        "student-attend_index",
        "student-attend_update",
        "student-attend_view",
        "student-category_create",
        "student-category_delete",
        "student-category_index",
        "student-category_update",
        "student-category_view",
        "student-club_create",
        "student-club_delete",
        "student-club_index",
        "student-club_update",
        "student-club_view",
        "student-exam_create",
        "student-exam_delete",
        "student-exam_index",
        "student-exam_update",
        "student-exam_view",
        "student-order_create",
        "student-order_delete",
        "student-order_index",
        "student-order_update",
        "student-order_view",
        "student-subject-selection_create",
        "student-subject-selection_delete",
        "student-subject-selection_index",
        "student-subject-selection_update",
        "student-subject-selection_view",
        "student-time-option_create",
        "student-time-option_delete",
        "student-time-option_index",
        "student-time-option_update",
        "student-time-option_view",
        "student-time-table_create",
        "student-time-table_delete",
        "student-time-table_index",
        "student-time-table_update",
        "student-time-table_view",
        "student_by-pinfl",
        "student_create",
        "student_delete",
        "student_export",
        "student_get",
        "student_import",
        "student_index",
        "student_me",
        "student_read",
        "student_time-option-not",
        "student_update",
        "student_view",
        "subject-access_create",
        "subject-access_delete",
        "subject-access_index",
        "subject-access_update",
        "subject-access_view",
        "subject-category_create",
        "subject-category_delete",
        "subject-category_index",
        "subject-category_update",
        "subject-category_view",
        "subject-content-mark_create",
        "subject-content-mark_delete",
        "subject-content-mark_index",
        "subject-content-mark_update",
        "subject-content-mark_view",
        "subject-content_create",
        "subject-content_delete",
        "subject-content_index",
        "subject-content_order",
        "subject-content_trash",
        "subject-content_trash-delete",
        "subject-content_types",
        "subject-content_update",
        "subject-content_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-topic-reference_create",
        "subject-topic-reference_delete",
        "subject-topic-reference_index",
        "subject-topic-reference_update",
        "subject-topic-reference_view",
        "subject-topic_create",
        "subject-topic_delete",
        "subject-topic_index",
        "subject-topic_update",
        "subject-topic_view",
        "subject-type_create",
        "subject-type_delete",
        "subject-type_index",
        "subject-type_update",
        "subject-type_view",
        "subject_create",
        "subject_delete",
        "subject_index",
        "subject_update",
        "subject_view",
        "survey-answer_create",
        "survey-answer_delete",
        "survey-answer_index",
        "survey-answer_update",
        "survey-answer_view",
        "survey-question_create",
        "survey-question_delete",
        "survey-question_index",
        "survey-question_update",
        "survey-question_view",
        "system_language",
        "system_settings",
        "table-store_create",
        "table-store_delete",
        "table-store_index",
        "table-store_update",
        "table-store_view",
        "teacher-access_content",
        "teacher-access_create",
        "teacher-access_delete",
        "teacher-access_free",
        "teacher-access_index",
        "teacher-access_update",
        "teacher-access_view",
        "teacher-checking-type_create",
        "teacher-checking-type_delete",
        "teacher-checking-type_index",
        "teacher-checking-type_update",
        "teacher-checking-type_view",
        "teacher-content_create",
        "teacher-content_delete",
        "teacher-content_index",
        "teacher-content_update",
        "teacher-content_view",
        "telegram_bot",
        "telegram_index",
        "test-get-data_hemis",
        "test-get-data_index",
        "test-get-data_index111",
        "test-get-data_view",
        "time-option_create",
        "time-option_delete",
        "time-option_index",
        "time-option_update",
        "time-option_view",
        "time-table_create",
        "time-table_delete",
        "time-table_index",
        "time-table_parent-null",
        "time-table_update",
        "time-table_view",
        "translate_create",
        "translate_delete",
        "translate_index",
        "translate_update",
        "translate_view",
        "user-access-type_create",
        "user-access-type_delete",
        "user-access-type_index",
        "user-access-type_update",
        "user-access-type_view",
        "user-access_create",
        "user-access_delete",
        "user-access_index",
        "user-access_update",
        "user-access_view",
        "user_create",
        "user_delete",
        "user_get",
        "user_index",
        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "user_update",
        "user_view",
        "vocation_create",
        "vocation_delete",
        "vocation_index",
        "vocation_update",
        "vocation_view",
        "week_create",
        "week_delete",
        "week_index",
        "week_update",
        "week_view",
        "work-rate_create",
        "work-rate_delete",
        "work-rate_index",
        "work-rate_update",
        "work-rate_view"

    ],

    /* O'quv bo'limi Admin */
    'edu_admin' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        "access-control_roles",

        "area_index",
        "area_view",
        "building_create",
        "building_index",
        "building_update",
        "building_view",
        "citizenship_index",
        "country_index",
        "country_view",
        "course_index",
        "course_view",
        "department_index",
        "direction_create",
        "direction_index",
        "direction_update",
        "direction_view",
        "edu-form_create",
        "edu-form_index",
        "edu-form_update",
        "edu-form_view",
        "edu-plan_create",
        "edu-plan_delete",
        "edu-plan_index",
        "edu-plan_update",
        "edu-plan_view",
        "edu-semestr-subject_create",
        "edu-semestr-subject_delete",
        "edu-semestr-subject_index",
        "edu-semestr-subject_update",
        "edu-semestr-subject_view",
        "edu-semestr_create",
        "edu-semestr_index",
        "edu-semestr_update",
        "edu-semestr_view",
        "edu-type_index",
        "edu-year_create",
        "edu-year_index",
        "edu-year_update",
        "edu-year_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-semeta_index",

        "exam-semeta_create",
        "exam-semeta_view",

        "exam-appeal_index",

        "exam-appeal-semeta_create",
        "exam-appeal-semeta_index",
        "exam-appeal-semeta_view",

        "exam-student_index",
        "exam-student_view",
        "exam-student_update",
        "exam-student_create",
        "exams-type_create",
        "exams-type_index",
        "exams-type_update",
        "exams-type_view",
        "exam_ad",
        "exam_appeal-distribution",
        "exam_create",
        "exam_distribution",
        "exam_generate-passwords",
        "exam_get-passwords",
        "exam_index",
        "exam_update",
        "exam_view",
        "faculty_create",
        "faculty_index",
        "faculty_update",
        "faculty_view",
        "hostel-app_index",
        "hostel-category-type_index",
        "hostel-category_index",
        "kafedra_create",
        "kafedra_index",
        "kafedra_update",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "para_create",
        "para_index",
        "para_update",
        "para_view",
        "password_index",
        "password_update",
        "password_view",
        "question-type_create",
        "question-type_index",
        "question-type_update",
        "question-type_view",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_view",
        "region_index",
        "region_view",
        "room_create",
        "room_free",
        "room_index",
        "room_update",
        "room_view",
        "semestr_index",
        "semestr_view",
        "statistic_checking",
        "statistic_student-count-by-faculty",
        "student_create",
        "student_index",
        "student_update",
        "student_view",
        "subject-category_create",
        "subject-category_index",
        "subject-category_update",
        "subject-category_view",
        "subject-content_index",
        "subject-content_types",
        "subject-content_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-type_create",
        "subject-type_index",
        "subject-type_update",
        "subject-type_view",
        "subject_create",
        "subject_index",
        "subject_update",
        "subject_view",
        "teacher-access_free",
        "teacher-access_index",
        "teacher-access_view",
        "teacher-access_update",

        "time-table_create",
        // "time-table_delete",
        "time-table_index",
        "time-table_parent-null",
        "time-table_update",
        "time-table_view",


        "time-option_create",
        "time-option_delete",
        "time-option_index",
        "time-option_update",
        "time-option_view",

        "user-access-type_index",
        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_status-list",
        "user_update",
        "user_view",
        "week_index",
        "week_view"
    ],

    /* O'quv bo'limi kontenthisi */
    'edu_moderator' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        // 'time-table_index',
        // 'time-table_create',
        // 'time-table_update',
        // 'time-table_view',
        // 'time-table_delete',
    ],

    /* O'quv bo'limi nazoratchi */
    'edu_editor' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////

        /**1 */


        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'user_status-list',
        'user_index',
        'user_create',
        'user_update',
        'user_view',
        'user_delete',
        /**
         * 
         */
        'languages_index',
        'teacher-access_index',
        'citizenship_index',
        'nationality_index',
        'course_index',
        'area_index',
        'region_index',
        'country_index',
        'area_view',
        'region_view',
        'country_view',

        'user-access-type_index',


        'building_index',
        'building_create',
        'building_update',
        'building_view',

        'room_index',
        'room_create',
        'room_update',
        'room_view',

        'edu-form_index',
        'edu-form_create',
        'edu-form_update',
        'edu-form_view',

        'para_index',
        'para_create',
        'para_update',
        'para_view',

        // 'exam_index',
        // 'exam_create',
        // 'exam_update',
        // 'exam_view',

        'exams-type_index',
        'exams-type_create',
        'exams-type_update',
        'exams-type_view',

        'subject-type_index',
        'subject-type_create',
        'subject-type_update',
        'subject-type_view',

        'subject-category_index',
        'subject-category_create',
        'subject-category_update',
        'subject-category_view',

        'edu-year_index',
        'edu-year_create',
        'edu-year_update',
        'edu-year_view',

        'edu-semestr_index',
        'edu-semestr_create',
        'edu-semestr_update',
        'edu-semestr_view',

        'question-type_index',
        'question-type_create',
        'question-type_update',
        'question-type_view',

        'direction_index',
        'direction_create',
        'direction_update',
        'direction_view',

        'faculty_index',
        'department_index',
        'faculty_create',
        'faculty_update',
        'faculty_view',

        'kafedra_index',
        'kafedra_create',
        'kafedra_update',
        'kafedra_view',

        'student_index',
        'student_create',
        'student_update',
        'student_view',


        // 'time-table_index',
        // 'time-table_create',
        // 'time-table_update',
        // 'time-table_view',
        // 'time-table_delete',
    ],

    /* O'quv bo'limi yordamchi */
    'edu_viewer' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////

        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'user_status-list',
        'user_index',
        'user_create',
        'user_update',
        'user_view',
        'user_delete',
        /**
         * 
         */
        'languages_index',
        'teacher-access_index',
        'citizenship_index',
        'nationality_index',
        'course_index',
        'area_index',
        'region_index',
        'country_index',
        'area_view',
        'region_view',
        'country_view',

        'user-access-type_index',


        'building_index',
        'building_create',
        'building_update',
        'building_view',

        'room_index',
        'room_create',
        'room_update',
        'room_view',

        'edu-form_index',
        'edu-form_create',
        'edu-form_update',
        'edu-form_view',

        'para_index',
        'para_create',
        'para_update',
        'para_view',

        // 'exam_index',
        // 'exam_create',
        // 'exam_update',
        // 'exam_view',

        'exams-type_index',
        'exams-type_create',
        'exams-type_update',
        'exams-type_view',

        'subject-type_index',
        'subject-type_create',
        'subject-type_update',
        'subject-type_view',

        'subject-category_index',
        'subject-category_create',
        'subject-category_update',
        'subject-category_view',

        'edu-year_index',
        'edu-year_create',
        'edu-year_update',
        'edu-year_view',

        'edu-semestr_index',
        'edu-semestr_create',
        'edu-semestr_update',
        'edu-semestr_view',

        'question-type_index',
        'question-type_create',
        'question-type_update',
        'question-type_view',

        'direction_index',
        'direction_create',
        'direction_update',
        'direction_view',

        'faculty_index',
        'department_index',
        'faculty_create',
        'faculty_update',
        'faculty_view',

        'kafedra_index',
        'kafedra_create',
        'kafedra_update',
        'kafedra_view',

        'student_index',
        'student_create',
        'student_update',
        'student_view',

    ],

    /* Talim sifati */
    'edu_quality' => [

        'user_oferta',
        "access-control_roles",
        "area_index",
        "area_view",
        // "building_create",
        "building_index",
        // "building_update",
        "building_view",
        "citizenship_index",
        "country_index",
        "country_view",
        "course_index",
        "course_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "faculty_index",
        "kafedra_index",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "password_index",
        "password_view",
        "region_index",
        "region_view",
        "room_index",
        "room_view",
        "subject-category_index",
        "subject-category_view",
        "subject-content-mark_index",
        "subject-content-mark_view",
        "subject-content_index",
        "subject-content_types",
        "subject-content_view",
        "subject-sillabus_index",
        "subject-sillabus_view",
        "subject-topic-reference_index",
        "subject-topic-reference_view",
        "subject-topic_index",
        "subject-topic_view",
        "subject-type_index",
        "subject-type_view",
        "subject_index",
        "subject_view",
        "teacher-access_index",
        "teacher-access_view",
        "teacher-content_create",
        "teacher-content_delete",
        "teacher-content_index",
        "teacher-content_update",
        "teacher-content_view",
        "user-access-type_index",
        "user_index",

        "kpi-category_index",
        "kpi-category_view",
        "kpi-data_view",
        "kpi-data_index",
        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "user_view",
        "week_index",
        "week_view",

        "time-table_index",
        "time-table_parent-null",
        "time-table_view",

        "para_index",
    ],


    /* Dekan huquqlari */
    'dean' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        "access-control_permissions",
        "access-control_roles",
        "area_index",
        "area_view",
        "building_index",
        "building_view",
        "citizenship_index",
        "citizenship_view",
        "country_index",
        "country_view",
        "course_index",
        "department_index",
        "department_types",
        "direction_create",
        "direction_delete",
        "direction_index",
        "direction_update",
        "direction_view",
        "edu-form_index",
        "edu-plan_create",
        "edu-plan_delete",
        "edu-plan_index",
        "edu-plan_update",
        "edu-plan_view",
        "edu-semestr-subject_create",
        "edu-semestr-subject_delete",
        "edu-semestr-subject_index",
        "edu-semestr-subject_update",
        "edu-semestr-subject_view",
        "edu-semestr_create",
        "edu-semestr_delete",
        "edu-semestr_index",
        "edu-semestr_update",
        "edu-semestr_view",
        "edu-type_index",
        "edu-year_index",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exams-type_index",
        // "exam_create",
        // "exam_delete",
        // "exam_index",
        // "exam_update",
        // "exam_view",
        "faculty_index",
        "faculty_view",
        "kafedra_create",
        "kafedra_delete",
        "kafedra_index",
        "kafedra_update",
        "kafedra_user-access",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_create",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "para_index",
        "para_view",

        "password_index",
        "password_update",

        "question_index",
        "question_status-update",
        "question_update",
        "question_view",

        'question_status-list',

        "region_index",
        "region_view",
        "room_free",
        "room_index",
        "room_view",

        "semestr_index",
        "semestr_update",
        "semestr_view",

        "student_create",
        "student_get",
        "student_delete",
        "student_index",
        "student_update",
        "student_view",
        "student-category_index",
        "student-category_view",

        "student_time-option-not",

        "subject-category_index",
        "subject-category_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-type_index",
        "subject-type_view",
        "subject_index",
        "subject_view",

        "subject-content_index",
        "subject-topic_index",
        "subject-content_view",
        "subject-topic_view",

        "teacher-access_free",
        "teacher-access_index",
        "teacher-access_view",

        // "time-table_create",
        // "time-table_delete",
        "time-table_index",
        "time-table_parent-null",
        // "time-table_update",
        "time-table_view",

        "user-access-type_index",
        "user-access_create",
        "user-access_delete",
        "user-access_index",
        "user-access_update",
        "user-access_view",
        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_status-list",
        "user_update",
        "user_view",

        "week_index",
        "week_view",

        'statistic_checking',



    ],
    /* Dekan huquqlari */

    /* Zam Dekan huquqlari */
    'dean_deputy' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'user_status-list',
        'user_index',
        'user_create',
        'user_update',
        'user_view',
        'user_delete',

        'user-access_index',
        'user-access_create',
        'user-access_update',
        'user-access_view',
        'user-access_delete',

        'notification_create',
        'notification_index',
        'notification_my',

        'region_index',
        'region_view',

        'nationality_index',
        'nationality_view',

        'languages_index',
        'languages_view',

        'country_index',
        'country_view',

        'area_index',
        'area_view',

    ],

    /* Kafedra mudiri */
    'mudir' => [

        'user_oferta',

        "time-table_index",
        "time-table_parent-null",
        "time-table_view",
        // "time-table_create",
        // "time-table_update",
        // "time-table_delete",

        "building_index",
        "room_index",
        "room_free",
        "teacher-access_free",
        "para_index",
        "week_index",
        "edu-plan_index",
        "edu-semestr_index",
        "edu-semestr-subject_index",


        "academic-degree_index",
        "academic-degree_view",
        "access-control_permissions",
        "access-control_roles",
        "area_index",
        "area_view",
        "citizenship_view",
        "country_index",
        "country_view",
        "course_index",
        "course_view",
        "degree-info_index",
        "degree-info_view",
        "degree_index",
        "degree_view",
        "department_index",
        "diploma-type_index",
        "diploma-type_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-appeal-semeta_create",
        "exam-appeal-semeta_index",
        "exam-appeal-semeta_view",
        "exam-checking_index",
        "exam-checking_update",
        "exam-checking_view",
        "exam-question_index",
        "exam-question_view",
        "exam-semeta_create",
        "exam-semeta_index",
        "exam-semeta_view",
        "exams-type_index",
        "exams-type_view",
        "exam_index",
        "exam_view",
        "faculty_index",
        "kafedra_index",
        "kafedra_view",
        "languages_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "partiya_index",
        "partiya_view",
        "password_index",
        "password_update",
        "password_view",
        "question-type_index",
        "question-type_view",
        "question_create",
        "question_delete",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_update",
        "question_view",
        "region_index",
        "region_view",
        "semestr_index",
        "statistic_checking",
        "subject-category_index",
        "subject-category_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-topic_create",
        "subject-topic_delete",
        "subject-topic_index",
        "subject-topic_update",
        "subject-topic_view",
        "subject-type_index",
        "subject-type_view",
        "subject_create",
        "subject_index",
        "subject_update",
        "subject_view",
        "teacher-access_index",
        "teacher-access_update",
        "user-access-type_index",
        "user-access_create",
        "user-access_delete",
        "user-access_index",
        "user-access_update",
        "user-access_view",
        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "user_update",
        "user_view",

    ],


    /* tutor tarbiyachi huquqlari */
    'tutor' => [

        'user_oferta',

        "area_index",
        "citizenship_index",
        "country_index",
        "course_index",
        "department_index",
        "department_types",
        "direction_index",
        "edu-form_index",
        "edu-plan_index",
        "edu-plan_view",
        "edu-type_index",
        "edu-year_index",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "faculty_index",
        "faculty_view",
        "kafedra_index",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",

        "password_index",
        "password_update",
        "password_view",
        "region_index",
        "student-category_index",
        "student-category_view",
        "student_create",
        "student_delete",
        "student_import",
        "student_index",
        "student_update",
        "student_view",
        "student_get",

        "student_time-option-not",

        "subject_index",
        "subject_view",

        "time-option_index",
        "time-option_view",
        "time-table_index",
        "time-table_parent-null",
        "time-table_update",
        "time-table_view",

        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "week_index",
        "week_view",
        'room_index',
        'room_view',
        'para_index',
        'para_view',
        "edu-semestr_index",
        "edu-semestr_view",
        "building_index",
        "building_view",
        "subject-type_index",
        "student-time-table_index",
        "student-time-table_view",
        "student-time-option_index",
        "student-time-option_view",

        "attend_index",
        "attend_create",
        "attend_update",

        "attend-reason_create",
        "attend-reason_delete",
        "attend-reason_index",
        "attend-reason_update",
        "attend-reason_view",

    ],


    /* Bo'lim boshlig'i */
    'dep_lead' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'notification_approved',
        'notification_status-list',

        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'user_logout',
        'user_me',



        'department_update',
        'department_view',



    ],


    /* Kadr */
    'hr' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',


        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",


        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        "region_index",
        "region_view",


        'department_index',
        'department_types',
        'department_view',
        // 'department_create',
        // 'department_update',
        // 'department_delete',

        'kafedra_index',
        'kafedra_view',
        // 'kafedra_create',
        // 'kafedra_update',
        // 'kafedra_delete',

        'faculty_index',
        'faculty_view',
        // 'faculty_create',
        // 'faculty_update',
        // 'faculty_delete',

        'user-access_index',
        'user-access_view',
        'user-access_create',
        'user-access_update',
        'user-access_delete',

        'table-store_index',
        'table-store_view',
        'table-store_create',
        'table-store_update',
        'table-store_delete',

        'work-rate_index',
        'work-rate_view',
        'work-rate_create',
        'work-rate_update',
        'work-rate_delete',

        'job-title_index',
        'job-title_view',
        'job-title_create',
        'job-title_update',
        'job-title_delete',

        'vocation_index',
        'vocation_view',
        'vocation_create',
        'vocation_update',
        'vocation_delete',

        'holiday_index',
        'holiday_view',
        'holiday_create',
        'holiday_update',
        'holiday_delete',

        "user-access-type_index",

        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_update",
        "user_view",

        "user_status-list",


    ],

    /* Kadr yordamchi */
    'hr_viewer' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'notification_approved',
        'notification_status-list',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'department_index',

        'department_view',
    ],

    /* Teacher */
    'teacher' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        "course_index",
        "exam-appeal_index",
        "exam-appeal_update",
        "exam-appeal_view",
        "exam-checking_appeal",
        "exam-checking_index",
        "exam-checking_update",
        "exam-checking_view",
        "exam-semeta_index",
        "exam-student_index",
        "exam-student_update",
        "exam-student_view",
        "exam-teacher-check_index",
        "exam-teacher-check_view",
        "exam_index",
        "exam_view",
        "kpi-category_extra",
        "kpi-category_index",
        // "kpi-data_create",
        // "kpi-data_delete",
        "kpi-data_index",
        // "kpi-data_update",
        "kpi-data_view",
        "lang-certificate-type_index",
        "lang-certificate-type_view",
        "lang-certificate_index",
        "lang-certificate_view",
        "languages_index",
        "notification_approved",
        "notification_index",
        "password_update",
        "question-type_index",
        "question_create",
        "question_delete",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_update",
        "question_view",
        "semestr_index",
        "subject-category_index",
        "subject-content_index",
        "subject-content_types",

        "subject-content_create",

        "subject-content_update",
        "subject-content_delete",
        "subject-content_view",
        "subject-sillabus_index",
        "subject-topic-reference_create",
        "subject-topic-reference_delete",
        "subject-topic-reference_index",
        "subject-topic-reference_update",
        "subject-topic-reference_view",
        "subject-topic_index",
        "subject-topic_view",
        "subject_index",
        "user_logout",
        "user_me",

        "teacher-access_index",
        "teacher-access_view",
        "time-table_index",
        "time-table_parent-null",
        "time-table_view",
        "week_index",
        "para_index",
        "attend_create",
        "attend_index",
        "attend_update",
        "attend_view",
        "exam-control_create",
        "exam-control_delete",
        "exam-control_update",
        "exam-control_view",
        "exam-control-student_index",
        "exam-control-student_update",
        "exam-control-student_view",
        "exam-control-student_create",


    ],

    /* Student */
    'student' => [

        'user_oferta',
        "user_self",
        "user_selfget",
        "para_index",
        'student_me',

        "access-control_permissions",
        "access-control_roles",
        "area_view",
        "building_view",
        "country_view",
        "course_index",
        "course_view",
        "direction_view",
        "edu-plan_view",
        "edu-semestr-subject-category-time_view",
        "edu-semestr-subject_index",
        "edu-semestr-subject_view",
        "edu-semestr_index",
        "edu-semestr_view",
        "edu-type_view",
        "edu-year_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-student-answer_create",
        "exam-student-answer_get-question",
        "exam-student-answer_index",
        "exam-student-answer_update",
        "exam-student-answer_view",
        "exam-student_index",
        "exam-student_update",
        "exam-student_view",
        "exams-type_view",
        "exam_index",
        "exam_view",

        'exam-appeal_view',
        // "exam-appeal_create",
        // 'exam-appeal_delete',
        // 'exam-appeal_update',

        "faculty_view",
        "kafedra_view",
        "languages_view",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "para_view",
        "password_index",

        "password_update",
        "region_view",
        "room_view",
        "semestr_index",
        "semestr_view",
        "student-exam_create",
        "student-exam_delete",
        "student-exam_index",
        "student-exam_update",
        "student-exam_view",

        "subject-category_index",
        "subject-category_view",
        "subject-content_index",
        "subject-topic_index",
        "subject-type_index",
        "subject-type_view",
        "subject-topic-reference_index",

        "subject_view",
        "time-table_index",
        "time-table_parent-null",
        "time-table_view",
        "user_logout",
        "user_me",
        "week_index",
        "week_view",

        'survey-answer_create',
        'survey-answer_update',
        'survey-question_index',

        'election_index',
        'election-vote_create',
        'election-vote_update',

        'hostel-app_index',
        'hostel-app_create',
        'hostel-app_update',
        'hostel-app_view',
        'hostel-app_delete',

        'hostel-doc_index',
        'hostel-doc_create',
        'hostel-doc_update',
        'hostel-doc_view',
        'hostel-doc_delete',

        'student-subject-selection_index',
        'student-subject-selection_create',
        'student-subject-selection_update',
        'student-subject-selection_view',
        'student-subject-selection_delete',

        'hostel-category-type_index',
        'hostel-category_index',

        "time-option_index",
        "time-option_view",

        "student-time-option_create",
        // "student-time-option_delete",
        "student-time-option_index",
        "student-time-option_view",

        "student-time-table_create",
        // "student-time-table_delete",
        "student-time-table_index",
        // "student-time-table_update",
        "student-time-table_view",

        'club-category_view',
        'club-category_index',
        'club_index',
        'club_view',
        'club-time_index',
        'club-time_view',

        'student-club_create',
        'student-club_delete',
        'student-club_view',
        "student-club_index",

        "exam-control-student_index",
        "exam-control-student_view",
        "exam-control-student_update",
        "exam-control-student_create",

    ],

    'contenter' => [

        'user_oferta',
        "user_self",
        "user_selfget",

        'access-control_roles',
        'area_index',
        'area_view',
        'region_index',
        "user-access-type_index",
        "teacher-access_index",
        'kafedra_index',
        'kafedra_user-access',
        'kafedra_view',
        // 'subject-content-mark_create',
        // 'subject-content-mark_delete',
        'subject-content-mark_index',
        // 'subject-content-mark_update',
        'subject-content-mark_view',
        'subject-content_index',
        'subject-content_order',
        'subject-content_trash',
        'subject-content_trash-delete',
        'subject-content_types',
        // 'subject-content_update',
        'subject-content_view',
        'subject-topic_index',
        'subject-topic_view',
        'subject-type_index',
        'subject-type_view',
        'subject_index',
        'subject_view',
        'user_index',
        'user_logout',
        'user_me',
        'user_status-list',
        'user_view',
        'teacher-content_index',
        'teacher-content_view'

    ],

    'time_table_plus' => [

        'user_oferta',

        // // "time-table_create",
        // "time-table_delete",
        // // "time-table_index",
        // "time-table_parent-null",
        // // "time-table_update",
        // "time-table_view",

    ],

    'content_assign' => [

        'user_oferta',

        "user_self",
        "user_selfget",
        "user_logout",
        "user_me",
        'user_index',
        'teacher-content_index',
        'teacher-content_view',
        'teacher-content_update',
        'teacher-content_create',
        'teacher-content_delete',
        'subject_index',
        'subject_view',

    ],

    'kpi_check' => [

        'user_oferta',
        // "access-control_roles",
        // "kpi-category_extra",
        // "kpi-category_index",
        // "kpi-category_update",
        // "kpi-category_view",

        // "kpi-data_index",
        // // "kpi-data_update",
        // "kpi-data_view",

        // "kpi-mark_create",
        // "kpi-mark_delete",
        // "kpi-mark_index",
        // "kpi-mark_update",
        // "kpi-mark_view",
        // "kpi-store_create",
        // "kpi-store_delete",
        // "kpi-store_index",
        // "kpi-store_update",
        // "kpi-store_view",
        // "lang-certificate-type_index",
        // "lang-certificate-type_update",
        // "lang-certificate-type_view",
        // "languages_index",
        // "notification_index",
        // "notification_my",
        // "region_index",
        // "subject-category_index",
        // "kafedra_index",
        // "user_index",
        // "user_logout",
        // "user_me",
        // "user_self",
        // "user_selfget",
        // "user_status-list",
        // "user_view"
    ],

    'student_time_table_plus' => [

        'user_oferta',
        // "student-time-table_create",
        // "student-time-table_delete",
        // "student-time-table_index",
        // "student-time-table_update",
        // "student-time-table_view",
    ],

    'kpi_plus' => [

        'user_oferta',

        // 'kpi-category_extra',
        // 'kpi-category_index',
        // 'kpi-category_view',
        // 'kpi-data_index',
        // 'kpi-data_update',
        // 'kpi-data_create',
        // 'kpi-data_view',
    ],

    'hostel' => [

        'user_oferta',

        "user_self",
        "user_selfget",
        "course_index",
        "faculty_index",
        "hostel-app_update",
        "hostel-app_index",
        "hostel-app_view",
        "hostel-category-type_create",
        "hostel-category-type_delete",
        "hostel-category-type_index",
        "hostel-category-type_update",
        "hostel-category-type_view",
        "hostel-category_create",
        "hostel-category_delete",
        "hostel-category_index",
        "hostel-category_update",
        "hostel-category_view",
        "hostel-doc_check",
        "hostel-doc_index",
        "hostel-doc_not",
        "hostel-doc_view",
        "notification_approved",
        "notification_create",
        "notification_delete",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_update",
        "notification_view",
        "student_view",
        "system_language",
        "user_logout",
        "user_me",

    ],

    'content_plus' => [

        'user_oferta',
        // "subject-content_create",
        // "subject-content_update",
        // "subject-content_delete",
        // "subject-content_view",
    ],

    'club' => [

        'user_oferta',
        "club-time_create",
        "club-time_delete",
        "club-time_index",
        "club-time_update",
        "club-time_view",
        "club-category_create",
        "club-category_delete",
        "club-category_index",
        "club-category_update",
        "club-category_view",
        "club_create",
        "club_delete",
        "club_index",
        "club_update",
        "club_view",
        "student-club_delete",
        "student-club_index",
        "student-club_view",
        "week_index",
        "week_view",

    ],
];
